### ISSUE TITLE
NG+

### ISSUE THREAD

**Issue by LiaNdrY** [Crackshell/heroes-english-history#2]
Thank you! I also noticed that until now I did not enter a variable for the text "**NG+**", which occurs in the tooltips.

![screenshot_1](https://user-images.githubusercontent.com/35012888/46213974-a64b2300-c342-11e8-9638-d08cbf5e2bbd.jpg)

Found the text "**NG+**" in the following files:
```
.\assets\scripts\GameModes\BossLevel.as
.\assets\scripts\GameModes\RandomLevel.as
.\assets\scripts\GameModes\Town.as
.\assets\scripts\GUI\PlayerMenu\Character.as
.\assets\scripts\GUI\PlayerMenu\Map.as
```

**Comment by codecat** [comment]
What do you intend to translate `NG+` to? Is it necessary?

**Comment by LiaNdrY** [comment]
This is certainly not critical, but the game already flashes the full translation of this concept, as well as its abbreviations, and this is the only place where it is not translated.

New Game+ = **NG+**
Новая Игра+ = **НИ+**

**Comment by codecat** [comment]
Good point. I'll have this fixed, thank you!

**Comment by codecat** [comment]
For what it's worth, some of those are Discord Rich Presence strings, which are untranslatable.

I've fixed the ones in UI though.
