### ISSUE TITLE
Typo in scripts

### ISSUE THREAD

**Issue by LiaNdrY** [Crackshell/heroes-english-history#3]
File "\assets\actors\pop\spider_2.unit"

The file contains ".bestiary.name.spider_1" instead of ".bestiary.name.spider_2"

Lines "dialogue.town.npc.generic.woman2.name" and "dialogue.town.npc.generic.woman2.1a" are found twice in the localization file.

And make the main localization file load after the localization file in mods so that it is easier to localize any mods.

**Comment by codecat** [comment]
Thanks for the report!

**Comment by codecat** [comment]
Fixed those 2 string issues, we'll be looking into the mod localization as well. 👍 

Are there any mods in particular you'd be interested in translating?

**Comment by LiaNdrY** [comment]
I would add to the main localization file a translation of all popular mods, as well as make translations to those that would be asked by subscribers of my main translation.
